# Generated by Django 4.1.7 on 2023-05-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_carouselimage_alter_brand_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselimage",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.product",
                verbose_name="Product",
            ),
        ),
    ]
