# Generated by Django 4.1.7 on 2023-05-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.FloatField(default=0, verbose_name="Total price"),
            preserve_default=False,
        ),
    ]
